/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "bztnzgobliugqnbcxztb"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6dG56Z29ibGl1Z3FuYmN4enRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk5NDE2NDMsImV4cCI6MjA5NTUxNzY0M30.C-648dnaQ557uImbH40xjkM2vBSq4zFjK-t2lxJ5Wig"